datamodule:
  dataset_path: ${r_path}/gdna/data/THuman2.0_processed
  data_list: ${r_path}/gdna/lib/dataset/thuman.csv
  cache_path: ${starting_path}
  num_workers: 16
  batch_size: 16
  points_per_frame: 2000
  load_img: false
  load_cache: false
  load_surface: false
  load_res: 256
  
